services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    environment:
      APP_URL: https://${DOMAIN_NAME}
    # ports:
    #   - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
    
    networks:
      - traefik_proxy
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel_web.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.beszel_web.entrypoints=web,websecure"
      # - "traefik.http.routers.beszel_web.tls=true"
      - "traefik.http.routers.beszel_web.tls.certresolver=myresolver"
      - "traefik.http.services.beszel_web.loadbalancer.server.port=8090"

      # ---------------------
      - "traefik.http.routers.beszel-www.rule=Host(`www.${DOMAIN_NAME}`)"
      - "traefik.http.routers.beszel-www.entrypoints=websecure"
      # - "traefik.http.routers.beszel-www.tls=true"
      - "traefik.http.routers.beszel-www.tls.certresolver=myresolver"
      - "traefik.http.routers.beszel-www.middlewares=beszel-www-redirect@docker"

      - "traefik.http.middlewares.beszel-www-redirect.redirectregex.regex=^https://www\\.${DOMAIN_NAME}(.*)"
      - "traefik.http.middlewares.beszel-www-redirect.redirectregex.replacement=https://${DOMAIN_NAME}$${1}"
      - "traefik.http.middlewares.beszel-www-redirect.redirectregex.permanent=true"


  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_agent_data:/var/lib/beszel-agent
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: ${DOMAIN_NAME}
      TOKEN: <token>
      KEY: "<key>"

networks:
  traefik_proxy:
    # Déclare le réseau externe
    external: true
